In [149]:
import pandas as pd

In [150]:
train = pd.read_csv("train.csv")
users = pd.read_csv("users.csv")

In [151]:
#Inner join train.csv and users.csv using user_id

data = pd.merge(left=train,right=users,left_on="user_id",right_on="user_id")

In [152]:
data.head()

,country_code,grass_date,user_id,subject_line_length,last_open_day,last_login_day,last_checkout_day,open_count_last_10_days,open_count_last_30_days,open_count_last_60_days,...,checkout_count_last_10_days,checkout_count_last_30_days,checkout_count_last_60_days,open_flag,row_id,attr_1,attr_2,attr_3,age,domain
0,4,2019-07-16 00:00:00+08:00,43,44,19,6,18,0,2,4,...,0,5,10,0,0,1.0,1.0,2.0,47.0,@gmail.com
1,4,2019-07-16 00:00:00+08:00,102,44,9,4,8,2,9,17,...,1,1,4,1,1,1.0,1.0,2.0,25.0,@hotmail.com
2,6,2019-07-16 00:00:00+08:00,177,49,14,5,5,0,4,12,...,5,19,27,0,2,NaN,1.0,0.0,NaN,@yahoo.com
3,1,2019-07-16 00:00:00+08:00,184,49,49,9,53,0,0,1,...,1,3,6,0,3,1.0,1.0,2.0,24.0,@yahoo.com
4,6,2019-07-16 00:00:00+08:00,221,49,227,6,221,0,0,0,...,0,0,0,0,4,NaN,1.0,0.0,NaN,@hotmail.com

In [153]:
#Dropping unimportant columns

data = data.drop(columns=['row_id'])
data.head()

,country_code,grass_date,user_id,subject_line_length,last_open_day,last_login_day,last_checkout_day,open_count_last_10_days,open_count_last_30_days,open_count_last_60_days,...,login_count_last_60_days,checkout_count_last_10_days,checkout_count_last_30_days,checkout_count_last_60_days,open_flag,attr_1,attr_2,attr_3,age,domain
0,4,2019-07-16 00:00:00+08:00,43,44,19,6,18,0,2,4,...,99,0,5,10,0,1.0,1.0,2.0,47.0,@gmail.com
1,4,2019-07-16 00:00:00+08:00,102,44,9,4,8,2,9,17,...,90,1,1,4,1,1.0,1.0,2.0,25.0,@hotmail.com
2,6,2019-07-16 00:00:00+08:00,177,49,14,5,5,0,4,12,...,119,5,19,27,0,NaN,1.0,0.0,NaN,@yahoo.com
3,1,2019-07-16 00:00:00+08:00,184,49,49,9,53,0,0,1,...,69,1,3,6,0,1.0,1.0,2.0,24.0,@yahoo.com
4,6,2019-07-16 00:00:00+08:00,221,49,227,6,221,0,0,0,...,5,0,0,0,0,NaN,1.0,0.0,NaN,@hotmail.com

In [154]:
# Checking any correlation

data.corr()

,country_code,user_id,subject_line_length,open_count_last_10_days,open_count_last_30_days,open_count_last_60_days,login_count_last_10_days,login_count_last_30_days,login_count_last_60_days,checkout_count_last_10_days,checkout_count_last_30_days,checkout_count_last_60_days,open_flag,attr_1,attr_2,attr_3,age
country_code,1.000000,-0.047390,-0.228446,0.072410,0.069744,0.058096,-0.088779,-0.095858,-0.095539,-0.014670,-0.022188,-0.026485,0.158945,0.006612,-0.040463,-0.055818,0.133018
user_id,-0.047390,1.000000,0.090311,-0.002713,-0.006046,-0.019741,-0.215780,-0.235338,-0.265182,-0.124446,-0.139839,-0.161749,-0.008082,-0.011673,0.003845,-0.268772,-0.024391
subject_line_length,-0.228446,0.090311,1.000000,-0.027971,-0.045970,-0.049144,-0.005046,-0.007230,-0.010097,0.010012,0.012583,0.011023,-0.057357,-0.001756,0.048804,-0.001994,-0.062709
open_count_last_10_days,0.072410,-0.002713,-0.027971,1.000000,0.877419,0.794886,0.040657,0.038676,0.036750,0.029375,0.027027,0.025011,0.515307,-0.009340,0.022555,-0.002847,0.082659
open_count_last_30_days,0.069744,-0.006046,-0.045970,0.877419,1.000000,0.938160,0.032019,0.037448,0.039500,0.022026,0.025572,0.026829,0.507853,-0.007631,0.026320,-0.002859,0.095314
open_count_last_60_days,0.058096,-0.019741,-0.049144,0.794886,0.938160,1.000000,0.029649,0.034864,0.044092,0.021949,0.023505,0.029054,0.477766,-0.013698,0.027400,0.001711,0.096920
login_count_last_10_days,-0.088779,-0.215780,-0.005046,0.040657,0.032019,0.029649,1.000000,0.938163,0.889673,0.406717,0.400422,0.389681,0.014023,0.010996,0.007910,0.226655,0.050613
login_count_last_30_days,-0.095858,-0.235338,-0.007230,0.038676,0.037448,0.034864,0.938163,1.000000,0.964382,0.363217,0.423100,0.421970,0.010134,0.011966,0.005174,0.240658,0.057420
login_count_last_60_days,-0.095539,-0.265182,-0.010097,0.036750,0.039500,0.044092,0.889673,0.964382,1.000000,0.344062,0.402575,0.438505,0.008633,0.012174,0.004036,0.253100,0.060317
checkout_count_last_10_days,-0.014670,-0.124446,0.010012,0.029375,0.022026,0.021949,0.406717,0.363217,0.344062,1.000000,0.860379,0.775574,0.015573,0.005649,0.009286,0.113888,0.025753
checkout_count_last_30_days,-0.022188,-0.139839,0.012583,0.027027,0.025572,0.023505,0.400422,0.423100,0.402575,0.860379,1.000000,0.928314,0.013419,0.006436,0.007525,0.128471,0.030378
checkout_count_last_60_days,-0.026485,-0.161749,0.011023,0.025011,0.026829,0.029054,0.389681,0.421970,0.438505,0.775574,0.928314,1.000000,0.010231,0.006866,0.007055,0.138146,0.035462
open_flag,0.158945,-0.008082,-0.057357,0.515307,0.507853,0.477766,0.014023,0.010134,0.008633,0.015573,0.013419,0.010231,1.000000,-0.016742,0.001605,-0.014235,0.103507
attr_1,0.006612,-0.011673,-0.001756,-0.009340,-0.007631,-0.013698,0.010996,0.011966,0.012174,0.005649,0.006436,0.006866,-0.016742,1.000000,-0.000968,0.015477,0.000468
attr_2,-0.040463,0.003845,0.048804,0.022555,0.026320,0.027400,0.007910,0.005174,0.004036,0.009286,0.007525,0.007055,0.001605,-0.000968,1.000000,-0.027124,-0.041632
attr_3,-0.055818,-0.268772,-0.001994,-0.002847,-0.002859,0.001711,0.226655,0.240658,0.253100,0.113888,0.128471,0.138146,-0.014235,0.015477,-0.027124,1.000000,-0.011608
age,0.133018,-0.024391,-0.062709,0.082659,0.095314,0.096920,0.050613,0.057420,0.060317,0.025753,0.030378,0.035462,0.103507,0.000468,-0.041632,-0.011608,1.000000

In [155]:
data.isnull().sum()

country_code                       0
grass_date                         0
user_id                            0
subject_line_length                0
last_open_day                      0
last_login_day                     0
last_checkout_day                  0
open_count_last_10_days            0
open_count_last_30_days            0
open_count_last_60_days            0
login_count_last_10_days           0
login_count_last_30_days           0
login_count_last_60_days           0
checkout_count_last_10_days        0
checkout_count_last_30_days        0
checkout_count_last_60_days        0
open_flag                          0
attr_1                         28192
attr_2                           279
attr_3                             0
age                            28192
domain                             0
dtype: int64

In [156]:
def isNaN(num):
    return num != num

In [157]:
for index,row in data.iterrows():
    if isNaN(data['attr_1'][index]):
        data['attr_1'][index] = 0
    if isNaN(data['attr_2'][index]):
        data['attr_2'][index] = 0
    if isNaN(data['attr_3'][index]):
        data['attr_3'][index] = 0
        
    if data['age'][index] < 16:
        data['age'][index] = 16
    
    if data['last_open_day'][index]== "Never open":
        data['last_open_day'][index] = -1
        
    if data['last_login_day'][index] == "Never login":
        data['last_login_day'][index] = -1
    
    if data['last_checkout_day'][index] == "Never checkout":
        data['last_checkout_day'][index] = -1

C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [158]:
data['age'].mean()
avg = data['age'].mean()

for index,row in data.iterrows():
    if isNaN(data['age'][index]):
        data['age'][index] = avg

C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [159]:
data[['last_open_day','last_checkout_day','last_login_day']] = data[['last_open_day','last_checkout_day',
                                                                     'last_login_day']].astype(int)

In [160]:
data.dtypes

country_code                     int64
grass_date                      object
user_id                          int64
subject_line_length              int64
last_open_day                    int32
last_login_day                   int32
last_checkout_day                int32
open_count_last_10_days          int64
open_count_last_30_days          int64
open_count_last_60_days          int64
login_count_last_10_days         int64
login_count_last_30_days         int64
login_count_last_60_days         int64
checkout_count_last_10_days      int64
checkout_count_last_30_days      int64
checkout_count_last_60_days      int64
open_flag                        int64
attr_1                         float64
attr_2                         float64
attr_3                         float64
age                            float64
domain                          object
dtype: object

In [161]:
for col in data:
    print(data[col].max())

7
2019-09-02 00:00:00+08:00
127925
75
808
18141
1445
31
92
135
254
735
1260
157
531
783
1
1.0
1.0
4.0
118.0
other

In [162]:
max1 = data['last_open_day'].max()
max2 =data['last_login_day'].max()
max3 = data['last_checkout_day'].max()

In [163]:
for index,row in data.iterrows():
    if data['last_open_day'][index]== -1:
        data['last_open_day'][index] = max1 + 1000
        
    if data['last_login_day'][index] == -1 :
        data['last_login_day'][index] = max2+ 10000
    
    if data['last_checkout_day'][index] == -1:
        data['last_checkout_day'][index] = max3 +1000

C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [164]:
for col in data:
    print(data[col].max())

7
2019-09-02 00:00:00+08:00
127925
75
1808
28141
2445
31
92
135
254
735
1260
157
531
783
1
1.0
1.0
4.0
118.0
other

In [166]:
for col in data:
    print(data[col].min())

1
2019-07-16 00:00:00+08:00
2
10
1
0
1
0
0
0
0
0
0
0
0
0
0
0.0
0.0
0.0
16.0
@163.com

In [167]:
data['age'].unique()

array([ 47.        ,  25.        ,  31.53961673,  24.        ,
        35.        ,  22.        ,  31.        ,  40.        ,
        26.        ,  33.        ,  16.        ,  38.        ,
        50.        ,  27.        ,  39.        ,  28.        ,
        30.        ,  21.        ,  23.        ,  29.        ,
        34.        ,  43.        ,  37.        ,  32.        ,
        36.        ,  42.        ,  45.        ,  41.        ,
        19.        ,  49.        ,  20.        ,  48.        ,
        54.        ,  46.        ,  17.        ,  52.        ,
       118.        ,  56.        ,  58.        ,  55.        ,
        51.        ,  44.        ,  18.        ,  72.        ,
        53.        ,  59.        ,  60.        ,  69.        ,
        63.        ,  62.        ,  65.        ,  66.        ,
        57.        ,  81.        ,  75.        ,  74.        ,
        76.        , 100.        ,  64.        ,  70.        ,
        68.        , 115.        ,  61.        ,  67.        ,
        92.        ,  95.        , 109.        ,  71.        ,
        80.        , 105.        ,  97.        , 110.        ,
       101.        ,  98.        , 114.        , 108.        ,
       107.        , 112.        ,  73.        ,  99.        ,
        93.        , 104.        ])

In [168]:
X = data[['country_code','subject_line_length','open_count_last_10_days','open_count_last_30_days',
         'open_count_last_60_days','login_count_last_10_days','login_count_last_30_days',
         'login_count_last_60_days','checkout_count_last_10_days','checkout_count_last_30_days',
         'checkout_count_last_60_days','attr_1','attr_2','attr_3','age']]
y=data['open_flag']

In [169]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)
#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(10,'Score'))  #print 10 best features

                          Specs          Score
4       open_count_last_60_days  208834.842684
3       open_count_last_30_days  142478.841547
2       open_count_last_10_days   65889.458531
0                  country_code    2058.278431
14                          age    1327.549872
1           subject_line_length     697.541656
7      login_count_last_60_days     576.775055
6      login_count_last_30_days     427.963569
5      login_count_last_10_days     310.918827
9   checkout_count_last_30_days     279.776971

In [204]:
# Using Feature selection(SelectKBest)

X = data[['open_count_last_60_days','open_count_last_30_days','open_count_last_10_days']]

In [170]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve
from sklearn.model_selection import learning_curve,GridSearchCV

In [205]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [206]:
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

predlogreg = logreg.predict(X_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predlogreg))
print("Score:",round(accuracy_score(y_test,predlogreg)*100,2))
print("Classification Report:",classification_report(y_test,predlogreg))

Confusion Matrix for Multinomial Naive Bayes:
[[12095   304]
 [ 1535   774]]
Score: 87.5
Classification Report:               precision    recall  f1-score   support

           0       0.89      0.98      0.93     12399
           1       0.72      0.34      0.46      2309

    accuracy                           0.87     14708
   macro avg       0.80      0.66      0.69     14708
weighted avg       0.86      0.87      0.86     14708

In [207]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_train,y_train)
predmnb = mnb.predict(X_test)
print("Confusion Matrix for Multinomial Naive Bayes:")
print(confusion_matrix(y_test,predmnb))
print("Score:",round(accuracy_score(y_test,predmnb)*100,2))
print("Classification Report:",classification_report(y_test,predmnb))

Confusion Matrix for Multinomial Naive Bayes:
[[12392     7]
 [ 2272    37]]
Score: 84.51
Classification Report:               precision    recall  f1-score   support

           0       0.85      1.00      0.92     12399
           1       0.84      0.02      0.03      2309

    accuracy                           0.85     14708
   macro avg       0.84      0.51      0.47     14708
weighted avg       0.84      0.85      0.78     14708

In [208]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
rmfr = RandomForestClassifier()
rmfr.fit(X_train,y_train)
predrmfr = rmfr.predict(X_test)
print("Confusion Matrix for Random Forest Classifier:")
print(confusion_matrix(y_test,predrmfr))
print("Score:",round(accuracy_score(y_test,predrmfr)*100,2))
print("Classification Report:",classification_report(y_test,predrmfr))

Confusion Matrix for Random Forest Classifier:
[[12002   397]
 [ 1482   827]]
Score: 87.22
Classification Report:               precision    recall  f1-score   support

           0       0.89      0.97      0.93     12399
           1       0.68      0.36      0.47      2309

    accuracy                           0.87     14708
   macro avg       0.78      0.66      0.70     14708
weighted avg       0.86      0.87      0.86     14708

In [209]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
preddt = dt.predict(X_test)
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(y_test,preddt))
print("Score:",round(accuracy_score(y_test,preddt)*100,2))
print("Classification Report:",classification_report(y_test,preddt))

Confusion Matrix for Decision Tree:
[[12043   356]
 [ 1554   755]]
Score: 87.01
Classification Report:               precision    recall  f1-score   support

           0       0.89      0.97      0.93     12399
           1       0.68      0.33      0.44      2309

    accuracy                           0.87     14708
   macro avg       0.78      0.65      0.68     14708
weighted avg       0.85      0.87      0.85     14708

In [210]:
# Support Vector Machine
from sklearn.svm import SVC
svm = SVC(random_state=101)
svm.fit(X_train,y_train)
predsvm = svm.predict(X_test)
print("Confusion Matrix for Support Vector Machines:")
print(confusion_matrix(y_test,predsvm))
print("Score:",round(accuracy_score(y_test,predsvm)*100,2))
print("Classification Report:",classification_report(y_test,predsvm))

Confusion Matrix for Support Vector Machines:
[[12038   361]
 [ 1476   833]]
Score: 87.51
Classification Report:               precision    recall  f1-score   support

           0       0.89      0.97      0.93     12399
           1       0.70      0.36      0.48      2309

    accuracy                           0.88     14708
   macro avg       0.79      0.67      0.70     14708
weighted avg       0.86      0.88      0.86     14708

In [211]:
# Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier
"""# parameter evaluation
gbe = GradientBoostingClassifier(random_state=0)
parameters = {
     'learning_rate': [0.05, 0.1, 0.5],
    'max_features': [0.5, 1],
    'max_depth': [3, 4, 5]}
gridsearch=GridSearchCV(gbe,parameters,cv=100,scoring='roc_auc')
gridsearch.fit(x,y)
print(gridsearch.best_params_)
print(gridsearch.best_score_)"""
#Boosting
gbi = GradientBoostingClassifier(learning_rate=0.1,max_depth=5,max_features=0.5,random_state=999999)
gbi.fit(X_train,y_train)
predgbi = gbi.predict(X_test)
print("Confusion Matrix for Gradient Boosting Classifier:")
print(confusion_matrix(y_test,predgbi))
print("Score:",round(accuracy_score(y_test,predgbi)*100,2))
print("Classification Report:",classification_report(y_test,predgbi))

Confusion Matrix for Gradient Boosting Classifier:
[[11999   400]
 [ 1410   899]]
Score: 87.69
Classification Report:               precision    recall  f1-score   support

           0       0.89      0.97      0.93     12399
           1       0.69      0.39      0.50      2309

    accuracy                           0.88     14708
   macro avg       0.79      0.68      0.71     14708
weighted avg       0.86      0.88      0.86     14708

In [212]:
# XGBoost Classifier
import xgboost
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
predxgb = xgb.predict(X_test)
print("Confusion Matrix for XGBoost Classifier:")
print(confusion_matrix(y_test,predxgb))
print("Score: ",round(accuracy_score(y_test,predxgb)*100,2))
print("Classification Report:")
print(classification_report(y_test,predxgb))

Confusion Matrix for XGBoost Classifier:
[[11980   419]
 [ 1398   911]]
Score:  87.65
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.97      0.93     12399
           1       0.68      0.39      0.50      2309

    accuracy                           0.88     14708
   macro avg       0.79      0.68      0.72     14708
weighted avg       0.86      0.88      0.86     14708

In [213]:
# MULTILAYER PERCEPTRON CLASSIFIER
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier()
mlp.fit(X_train,y_train)
predmlp = mlp.predict(X_test)
print("Confusion Matrix for Multilayer Perceptron Classifier:")
print(confusion_matrix(y_test,predmlp))
print("Score:",round(accuracy_score(y_test,predmlp)*100,2))
print("Classification Report:")
print(classification_report(y_test,predmlp))

Confusion Matrix for Multilayer Perceptron Classifier:
[[11970   429]
 [ 1377   932]]
Score: 87.72
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.97      0.93     12399
           1       0.68      0.40      0.51      2309

    accuracy                           0.88     14708
   macro avg       0.79      0.68      0.72     14708
weighted avg       0.86      0.88      0.86     14708

In [219]:
test = pd.read_csv("test.csv")

In [220]:
test.head()

,country_code,grass_date,user_id,subject_line_length,last_open_day,last_login_day,last_checkout_day,open_count_last_10_days,open_count_last_30_days,open_count_last_60_days,login_count_last_10_days,login_count_last_30_days,login_count_last_60_days,checkout_count_last_10_days,checkout_count_last_30_days,checkout_count_last_60_days,row_id
0,6,2019-09-03 00:00:00+08:00,0,35,27,2,13,2,3,4,10,34,134,0,6,18,0
1,6,2019-09-03 00:00:00+08:00,130,35,7,5,383,1,1,1,5,5,5,0,0,0,1
2,5,2019-09-03 00:00:00+08:00,150,25,34,1,3,0,0,0,13,19,38,2,2,2,2
3,1,2019-09-03 00:00:00+08:00,181,36,63,5,5,0,0,0,43,110,173,2,5,5,3
4,5,2019-09-03 00:00:00+08:00,192,23,6,5,54,0,0,0,4,12,39,0,0,2,4

In [221]:
test = pd.merge(left=test,right=users,left_on="user_id",right_on="user_id")

In [222]:
test.isnull().sum()

country_code                       0
grass_date                         0
user_id                            0
subject_line_length                0
last_open_day                      0
last_login_day                     0
last_checkout_day                  0
open_count_last_10_days            0
open_count_last_30_days            0
open_count_last_60_days            0
login_count_last_10_days           0
login_count_last_30_days           0
login_count_last_60_days           0
checkout_count_last_10_days        0
checkout_count_last_30_days        0
checkout_count_last_60_days        0
row_id                             0
attr_1                         21233
attr_2                           168
attr_3                             0
age                            21233
domain                             0
dtype: int64

In [223]:
test.head()

,country_code,grass_date,user_id,subject_line_length,last_open_day,last_login_day,last_checkout_day,open_count_last_10_days,open_count_last_30_days,open_count_last_60_days,...,login_count_last_60_days,checkout_count_last_10_days,checkout_count_last_30_days,checkout_count_last_60_days,row_id,attr_1,attr_2,attr_3,age,domain
0,6,2019-09-03 00:00:00+08:00,0,35,27,2,13,2,3,4,...,134,0,6,18,0,NaN,1.0,0.0,NaN,@gmail.com
1,6,2019-09-03 00:00:00+08:00,130,35,7,5,383,1,1,1,...,5,0,0,0,1,NaN,1.0,0.0,NaN,@gmail.com
2,5,2019-09-03 00:00:00+08:00,150,25,34,1,3,0,0,0,...,38,2,2,2,2,1.0,1.0,2.0,33.0,@gmail.com
3,1,2019-09-03 00:00:00+08:00,181,36,63,5,5,0,0,0,...,173,2,5,5,3,1.0,1.0,2.0,22.0,@yahoo.com
4,5,2019-09-03 00:00:00+08:00,192,23,6,5,54,0,0,0,...,39,0,0,2,4,NaN,1.0,0.0,NaN,@gmail.com

In [224]:
for index,row in test.iterrows():
    if isNaN(test['attr_1'][index]):
        test['attr_1'][index] = 0
    if isNaN(test['attr_2'][index]):
        test['attr_2'][index] = 0
    if isNaN(test['attr_3'][index]):
        test['attr_3'][index] = 0
    if  test['age'][index] < 16:
        test['age'][index] = 16
        
    if test['last_open_day'][index]== "Never open":
        test['last_open_day'][index] = -1
        
    if test['last_login_day'][index] == "Never login":
        test['last_login_day'][index] = -1
    
    if test['last_checkout_day'][index] == "Never checkout":
        test['last_checkout_day'][index] = -1

C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [225]:
test[['last_open_day','last_checkout_day','last_login_day']] = test[['last_open_day','last_checkout_day',
                                                                     'last_login_day']].astype(int)

for col in test:
    print(test[col].max())

7
2019-09-29 00:00:00+08:00
127922
79
812
18165
1462
30
79
120
329
746
1300
252
404
609
55969
1.0
1.0
4.0
118.0
other

In [226]:
test_age = test['age'].mean()

max4 = data['last_open_day'].max()
max5 =data['last_login_day'].max()
max6 = data['last_checkout_day'].max()

for index,row in test.iterrows():
    if isNaN(test['age'][index]):
        test['age'][index] = test_age
        
    if test['last_open_day'][index] == -1:
        test['last_open_day'][index] = max4 + 1000
    if test['last_login_day'][index] == -1:
        test['last_login_day'][index] = max5 + 10000
    if test['last_checkout_day'][index] == -1:
        test['last_checkout_day'][index] = max6 + 1000

C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Andy_uni\anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [197]:
testing = test[['country_code','subject_line_length','open_count_last_10_days','open_count_last_30_days',
         'open_count_last_60_days','login_count_last_10_days','login_count_last_30_days',
         'login_count_last_60_days','checkout_count_last_10_days','checkout_count_last_30_days',
         'checkout_count_last_60_days','attr_1','attr_2','attr_3','age']]

In [227]:
# Using SelectKBest feature selection
testing = test[['open_count_last_60_days','open_count_last_30_days','open_count_last_10_days']]

In [198]:
test['open_flag']=""

test['open_flag'] = gbi.predict(testing)

In [199]:
test.head()

,country_code,grass_date,user_id,subject_line_length,last_open_day,last_login_day,last_checkout_day,open_count_last_10_days,open_count_last_30_days,open_count_last_60_days,...,checkout_count_last_10_days,checkout_count_last_30_days,checkout_count_last_60_days,row_id,attr_1,attr_2,attr_3,age,domain,open_flag
0,6,2019-09-03 00:00:00+08:00,0,35,27,2,13,2,3,4,...,0,6,18,0,0.0,1.0,0.0,31.361891,@gmail.com,0
1,6,2019-09-03 00:00:00+08:00,130,35,7,5,383,1,1,1,...,0,0,0,1,0.0,1.0,0.0,31.361891,@gmail.com,0
2,5,2019-09-03 00:00:00+08:00,150,25,34,1,3,0,0,0,...,2,2,2,2,1.0,1.0,2.0,33.000000,@gmail.com,0
3,1,2019-09-03 00:00:00+08:00,181,36,63,5,5,0,0,0,...,2,5,5,3,1.0,1.0,2.0,22.000000,@yahoo.com,0
4,5,2019-09-03 00:00:00+08:00,192,23,6,5,54,0,0,0,...,0,0,2,4,0.0,1.0,0.0,31.361891,@gmail.com,0

In [200]:
test=test[['row_id','open_flag']]

In [201]:
test.head()

   row_id  open_flag
0       0          0
1       1          0
2       2          0
3       3          0
4       4          0

In [203]:
test.to_csv(r'C:\Users\Andy_uni\Desktop\submission(marketing).csv', index = False, header=True)